#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/movext.h"
#include "data-mov/cltd.h"
#include "data-mov/leave.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"

#include "call/call.h"
#include "data-mov/push.h"
#include "logic/test.h"
#include "jump/je.h"
#include "arith/cmp.h"
#include "data-mov/pop.h"
#include "return/ret.h"
#include "arith/sub.h"
#include "jump/jmp.h"
#include "jump/jbe.h"
#include "arith/add.h"
#include "arith/adc.h"
#include "logic/setne.h"
#include "jump/jne.h"
#include "jump/jle.h"
#include "jump/jg.h"
#include "jump/jl.h"
#include "jump/jge.h"
#include "string/lods.h"
#include "string/scas.h"
#include "arith/sbb.h"
#include "string/stos.h"
#include "string/movs.h"
#include "jump/ja.h"
#include "jump/js.h"
#include "jump/jns.h"

